# Generated by Django 6.0.7 on 2026-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='covers/default_cover.jpg', upload_to='covers/'),
        ),
    ]
